apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pghero.name" . }}
  labels:
    {{- include "pghero.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.url }}:{{ .Values.database.port }}/{{ .Values.database.dbName }}"
{{- with .Values.secret.env }}
  {{- toYaml . | nindent 2 }}
{{- end }}
